module.exports = {
  apps: [
    {
      name: "openagent-gateway",
      script: "src/index.ts",
      args: "gateway",
      interpreter: "bun",
      exec_mode: "fork",
      instances: 1,
      // Watch src/ for self-evolution restarts; ignore user-space (uses dynamic import)
      watch: ["src"],
      ignore_watch: ["node_modules", "data", "logs", "dist", "user-space", "*.db*"],
      watch_delay: 2000,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PATH: `${process.env.HOME}/.bun/bin:${process.env.PATH}`,
      },
      error_file: "./logs/gateway-error.log",
      out_file: "./logs/gateway-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "openagent-worker",
      script: "src/worker.ts",
      interpreter: "bun",
      exec_mode: "fork",
      instances: 1,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PATH: `${process.env.HOME}/.bun/bin:${process.env.PATH}`,
      },
      error_file: "./logs/worker-error.log",
      out_file: "./logs/worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
  ],
};
